### ISSUE TITLE
Doesn't work with 14.7.4

### ISSUE THREAD

**Issue by johannest** [vaadin-component-factory/popup#12]
`﻿Caused by: java.lang.NoSuchMethodError: 'org.jsoup.nodes.Element org.jsoup.nodes.Element.traverse(org.jsoup.select.NodeVisitor)'
at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.inspectTwoWayBindings(TemplateDataAnalyzer.java:244) ~[flow-server-2.7.3.jar:2.7.3]
at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:233) ~[flow-server-2.7.3.jar:2.7.3]
at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:96) ~[flow-server-2.7.3.jar:2.7.3]
at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:91) ~[flow-server-2.7.3.jar:2.7.3]
at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:106) ~[flow-server-2.7.3.jar:2.7.3]
at com.vaadin.componentfactory.Popup.<init>(Popup.java:43) ~[popup-2.2.5.jar:1.5.0]`

**Comment by johannest** [comment]
Was probably caused by some other dependency
