### ISSUE TITLE
Popup not usable with Vaadin24, plugin v24.0.4

### ISSUE THREAD

**Issue by timothygruetzner** [vaadin-component-factory/popup#20]
It seems like plugin version 24.0.4 does not work correctly with Vaadin 24.4.3.

When creating the popup like `popup.setFor(id)` and the corresponding button with the same ID is clicked, nothing at all happens.
When programatically opening the poup via `popup.setOpened(true)`, the following JS error appears on the browser console:

```
Uncaught TypeError: $0.show is not a function
    at Object.eval (eval at Ot (FlowClient.js:1043:101), <anonymous>:3:11)
    at Ot (FlowClient.js:1043:166)
    at Nt (FlowClient.js:995:277)
    at Lt (FlowClient.js:613:57)
    at pr (FlowClient.js:526:18)
    at Lr.Mr [as cb] (FlowClient.js:1052:19660)
    at sB (FlowClient.js:964:221)
    at sr (FlowClient.js:1047:303)
    at Hr.Ir [as C] (FlowClient.js:1052:19426)
    at Ok (FlowClient.js:439:29)
    at kr (FlowClient.js:1050:1162)
    at lr (FlowClient.js:1033:403)
    at At.Ct [as kb] (FlowClient.js:1052:22893)
    at SB.TB [as J] (FlowClient.js:1052:35937)
    at XMLHttpRequest.<anonymous> (FlowClient.js:627:63)
    at Eb (FlowClient.js:458:29)
    at Hb (FlowClient.js:918:56)
    at XMLHttpRequest.<anonymous> (FlowClient.js:644:46)
```

Find an example of what I'm doing below:
```
VerticalLayout v = new VerticalLayout();
Popup popup = new Popup();
popup.add(new H1("Test Text"));
popup.setFor("test-btn");

Button testBtn = new Button("Open");
testBtn.setId("test-btn");
testBtn.addClickListener(e -> popup.setOpened(true));

v.add(testBtn, popup);
```

Am I using incompatible versions? I'm not using the latest version of the popup, as the Vaadin Add-on Directory mentions plugin 24.0.4 to be used with Vaadin 24.
